LuckyLibraryBundle:
    resource: "@LuckyLibraryBundle/Controller/"
    type:     annotation
    prefix:   /

default:
    pattern:      /
    defaults:     { _controller: LuckyLibraryBundle:Default:list, page: 1 }

list:
    pattern:      /book/page/{page}
    defaults:     { _controller: LuckyLibraryBundle:Default:list, page: 1 }

description:
    pattern:      /book/info/{id}
    defaults:     { _controller: LuckyLibraryBundle:Default:info, id: 1 }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
